require "c8dasm/assemblies/asm_base"
require "c8dasm/assemblies/asm0"
require "c8dasm/assemblies/asm1"
require "c8dasm/assemblies/asm2"
require "c8dasm/assemblies/asm3"
require "c8dasm/assemblies/asm4"
require "c8dasm/assemblies/asm6"
require "c8dasm/assemblies/asm7"
require "c8dasm/assemblies/asm8"
require "c8dasm/assemblies/asma"
require "c8dasm/assemblies/asmc"
require "c8dasm/assemblies/asmd"
require "c8dasm/assemblies/asme"
require "c8dasm/assemblies/asmf"

